{{- if .Values.global.signingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logos.signingSecretName" . }}
  labels:
    {{- include "logos.labels" . | nindent 4 }}
type: Opaque
data:
  signing-secret: {{ .Values.global.signingSecret | b64enc }}
{{- end }}
---
{{- if .Values.global.apiSigningSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logos.apiSigningSecretName" . }}
  labels:
    {{- include "logos.labels" . | nindent 4 }}
type: Opaque
data:
  api-signing-secret: {{ .Values.global.apiSigningSecret | b64enc }}
{{- end }}